run_type = "staged_learning"
device = "cuda:0"
tb_logdir = "tb_logs_armC"
json_out_config = "_armC_resolved.json"
seed = 42

[parameters]
prior_file = "/home/donmigcage/Research/priors/reinvent.prior"
agent_file = "/home/donmigcage/Research/priors/reinvent.prior"
summary_csv_prefix = "armC_generation"
use_checkpoint = false
batch_size = 64

[learning_strategy]
type = "dap"
sigma = 120
rate = 0.0001

[[stage]]
chkpt_file = "armC_stage1.chkpt"
max_steps = 100

[stage.scoring]
type = "geometric_mean"

[[stage.scoring.component]]
[stage.scoring.component.ExternalProcess]
[[stage.scoring.component.ExternalProcess.endpoint]]
name = "Bridge_Affinity"
weight = 0.7
[stage.scoring.component.ExternalProcess.endpoint.params]
executable = "/home/donmigcage/miniconda3/envs/reinvent4/bin/python"
args = "/home/donmigcage/Research/vina_scorer_armC.py"
property = "bridge_score"

[[stage.scoring.component]]
[stage.scoring.component.QED]
[[stage.scoring.component.QED.endpoint]]
name = "QED"
weight = 0.2

[[stage.scoring.component]]
[stage.scoring.component.MolecularWeight]
[[stage.scoring.component.MolecularWeight.endpoint]]
name = "MW"
weight = 0.1
[stage.scoring.component.MolecularWeight.endpoint.transform]
type = "double_sigmoid"
high = 500.0
low = 150.0
coef_div = 500.0
coef_si = 20.0
coef_se = 20.0
